name = "ThreadedSparseArrays"
uuid = "59d54670-b8ac-4d81-ab7a-bb56233e17ab"
authors = ["Stefanos Carlstr√∂m <stefanos.carlstrom@gmail.com>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.4"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "StableRNGs"]
